export const activitiesData = [
  {
    title: "30A-Beaches-South Walton Activities",
    type: "checkbox",
    options: [
      "30A Bike 19 Mile Bike Path",
      "Big Daddy's Bike Rental",
      "Blue Mountain Beach",
      "Camp Helen State Park",
      "Deer Lake State Park",
      "Emerald Coast Pedal Tours",
      "Emerald Coast Wine Cellars",
      "Fishy Booty Charters",
      "Fusion Art Glass Gallery",
      "Goatfeathers Seafood Market",
      "Grand Boulevard",
      "Grayton Beach State Park",
      "Kitchenique",
      "Rosemary Beach",
      "Santa Rosa Beach",
      "Santa Rosa Golf Club",
      "Seaside Beach",
      "SunQuest Cruises",
      "Surfside Spa",
      "Timpoochee Trail",
      "Topsail Beach State Preserve",
       "YOLO Board and Bike",
     
    ],
  },
  {
    title: "30A-Beaches-South Walton Restaurants",
    type: "checkbox",
    options: [
      "723 Whiskey Bravo",
      "Angelina's Pizzeria",
      "Basmati's Asian Cuisine",
      "Bijoux",
      "Borago Restaurant",
      "Bud & Alley's",
      "Cafe Thirty-A",
      "Christiano's",
      "Cowgirl Kitchen",
      "Fish Out of Water",
      "George's At Alys Beach",
      "Great Southern Cafe",
      "La Loba's Bakery",
      "Marie's Bistro",
      "Nick's on the Beach",
      "Restaurant Paradis",
      "The Bay",
      "The Creamery",
      "The Red Bar",
      "Trebeache",
      "Vue on 30A"
    ],
  },
   {
    title: "Anna Maria Activities",
    type: "checkbox",
     options: []
   },
    {
    title: "Anna Maria Restaurants",
    type: "checkbox",
     options: []
   },
   {
    title: "Bradenton Beach Activities",
    type: "checkbox",
    options: [
      "Chasers",
      "Cinema Plus",
      "Divers Emporium",
      "Foxwood Country Club",
      "Goofy Golf",
      "Grayton Beach",
      "Marquis Cinema 10",
      "Panhandle Opry",
      "Peadon Distillery",
      "Reel Talk Charters",
      "Rocky Bayou State Park",
      "Scraps Suds & Grub",
      "Shoal River Bowling",
      "Splash Pad",
      "Turkey Creek Trail",
      "Twin Hills Park",
      "Wildlife Refuge Park"
    ],
  },
  {
    title: "Bradenton Beach Activities",
    type: "checkbox",
     options: []
   },
    {
    title: "Bradenton Beach Restaurants",
    type: "checkbox",
     options: []
   },
    {
    title: "Crestview Florida Restaurants",
    type: "checkbox",
    options: [
      "Azteca Mexican",
      "Bamboo Sushi Bar",
      "Beef 'O' Brady's",
      "Desi's",
      "Emerald Isle Seafood",
      "Hideaway",
      "Hot Dog Shoppe",
      "Hot Kim Chi",
      "Hub City Smokehouse",
      "Hunan Chinese",
      "Jin Jin China",
      "La Rumba",
      "Mia's Italian",
      "Pounders Hawaiian",
      "Ryan's",
      "Samuel's Roadhouse",
      "Uncle Bill's",
      "Wayne's Catfish House",
      "Wild Olive"
    ],
    
},
 {
    title: "Dauphin Island Activities",
    type: "checkbox",
    options: [
      "Audubon Bird Sanctuary",
      "Capt. Mike's Deep Sea Fishing",
      "Dauphin Island Park & Beach Board",
      "FinAtics Inshore Fishing Charters",
      "Fort Gaines",
      "Indian Shell Mound Park",
      "Isle Dauphine Golf Club",
      "Mobile Bay Ferry",
      "Southern Drawl Charters",
      "The Estuarium"
    ],
  },
   {
    title: "Dauphin Island Restaurants",
    type: "checkbox",
    options: [
      "Barnacle Bills Marina Grill",
      "Billy Goat Concessions LLC",
      "Dority's Bar & Grill",
      "Indian Mound Park",
      "Island Rainbow",
      "Islanders Restaurant",
      "JT's Sunset Grill",
      "Miguel's Beach'n Baja",
      "Pirate's Pleasure",
      "Subway"
    ],
  },
   {
    title: "Destin Florida Activities",
    type: "checkbox",
    options: [
      "Airboat Adventures",
      "AMC Theatre",
      "Backlash Charters",
      "Bart Rockett Magic Theater",
      "Baytowne Adventure Zone",
      "Big Kahuna Water Park",
      "Bike Rentals",
      "Blackwater Canoe Rental",
      "Blast Arcade & Laser Maze",
      "Buccaneer Pirate Ship",
      "Charter Boats",
      "Crab Island Dolphin Tours",
      "Deep Sea Fishing Party Boat",
      "Destin Beach Parasail",
      "Destin Float Spa Experience",
      "Destin Florida Beach Helicopters",
      "Destin Harbor",
      "Destin Paddleboard Rental",
      "Destin Snorkeling Excursion",
      "Destin Snorkle",
      "Dockside Parasailing",
      "Dockside Watersports",
      "Dolphin Cruise",
      "Dolphin Watch & History Cruise",
      "Emerald Coast Scuba",
      "Escape Zone 60",
      "Fishing with Kids",
      "Gator Country Alligator Park",
      "Golf Cart Rental",
      "Gulfarium Marine Adventure Park",
      "Horseback Trail Rides",
      "Hydrojet Thrill Ride",
      "Just Chute Me",
      "Kelly Plantation",
      "Local Fitness Center",
      "Mobile Massage Therapy",
      "Mobile Sports LLC",
      "Original Sea Blaster",
      "Party Boats",
      "Pelican Adventures",
      "Private Sailing Excursion",
      "Reel Deal Charters",
      "Sandestin Dining/Dancing Cruise",
      "Sea Blaster",
      "Shark Fishing Charter",
      "Southern Star Dolphin Cruises",
      "SunQuest Cruises",
      "SunVenture Cruises",
      "The Kayak Experience",
      "THE TRACK - GO Carts",
      "Waverunner Rental/Wet N Wild",
      "Wet N Wild Parasailing",
      "Xtreme H2O Sports"
    ],
  },
  {
    title: "Destin Florida Restaurants",
    type: "checkbox",
    options: [
      "AJ’s Seafood & Oyster Bar",
      "Alatapatatas",
      "Another Broken Egg Cafe",
      "Beach Walk Cafe",
      "Boathouse Oyster Bar",
      "Bonefish Grill",
      "Boshamps Seafood House",
      "Bric a Brac",
      "Brotula's Seafood & Steamer",
      "Bubba Gump Shrimp Co.",
      "Buck's Smokehouse",
      "Callahan's Restaurant & Deli",
      "Capriccio Cafe",
      "China One",
      "Crab Island Cantina",
      "Crust Pizzeria",
      "Dewey Destin Seafood",
      "Dewey Destin's Harborside",
      "Donut Hole Bakery Cafe",
      "Fudpuckers Bar & Grill",
      "Fuji Seafood Buffet",
      "Gilligan's Seafood",
      "Graffiti & The Funky Blues Shack",
      "Hadashi Sushi Bar at Hilton",
      "Hammerheads Bar & Grill",
      "Harbor Docks",
      "Hog's Breath Saloon",
      "IHOP",
      "Island Wing Company",
      "Jackacuda's Seafood & Sushi",
      "Jasmine Thai",
      "Jester Mardi Gras Daiquiris",
      "Joe's Crab Shack",
      "La Paz",
      "Lighthouse Restaurant",
      "Louisiana Lagniappe",
      "LuLu's Destin FL",
      "Mama Sherry's Pizza",
      "Margaritaville",
      "Marina Cafe",
      "McGuire's Irish Pub",
      "Mellow Mushroom",
      "Merlins Pizza",
      "Mimmo's",
      "Noonies Thai Cafe",
      "Original La Famiglia",
      "Osaka Japanese Hibachi",
      "Palm Grille",
      "Pepitos Mexican Restaurant",
      "Pompano Joe's",
      "Ruth's Chris Steak House",
      "Shrimp Basket",
      "Thai Delights Restaurant",
      "The Back Porch",
      "The Breakfast Table",
      "The Crab Trap",
      "The Surf Hut",
      "Vinnie Mc Guire's Pizza",
      "Wingstop",
      "World Of Beers"
    ],
  },
  {
    title: "Forgotten Coast Activities",
    type: "checkbox",
    options: [
      "Big Time Charters",
      "Bluewater Outriggers",
      "Cape San Blas Lighthouse",
      "Capt Alan's Sea Escape",
      "Dalys Watersports",
      "Floridaze Adventures",
      "Happy Ours Kayak",
      "Horseback Riding",
      "Johnson Boys Fishing",
      "No Worries Beach Service",
      "Rockin M Ranch",
      "Saltwater Obsessions",
      "Spa Pur",
      "St James Bay Golf Club",
      "St Joseph Bay Buffer Preserve",
      "St. Joe Patio",
      "St. Joseph Bay"
    ],
  },
   {
    title: "Forgotten Coast Restaurants",
    type: "checkbox",
    options: [
      "Cone Heads",
      "Golden Dragon",
      "Indian Pass Raw Bar",
      "Provision",
      "Shoobies",
      "Skully's Boil",
      "The Crooked River Grill",
      "Tiki Grill",
      "Up The Creek"
    ],
  },
  {
    title: "Fort Morgan Alabama Activities",
    type: "checkbox",
    options: [
      "Alabama Coastal Birding Trail",
      "Behind the Pines",
      "Bon Secour Wildlife Refuge",
      "Chill Time Charters",
      "Corsair Charters",
      "Kiva Dunes Golf Club",
      "Lakewood Golf Club",
      "Mobile Bay Ferry",
      "Oak Hollow Farm",
      "Peninsula Golf & Racquet Club",
      "Punta Clara Candy Kitchen",
      "The Fort Historic Site",
      "Village Point Park Preserve",
      "Weeks Bay"
    ],
  },
  {
    title: "Fort Morgan Alabama Restaurants",
    type: "checkbox",
    options: [
      "Big O's Dog House Grill",
      "Captain Morgan's Hideaway",
      "Coast Restaurant",
      "Fort Morgan Pizza",
      "Ocean's Pizza",
      "Sassy Bass Amazin' Grill",
      "Tacky Jack's",
      "The Village Lawn",
      "Village Creamery",
      "Village Hideaway"
    ],
  }, {
    title: "Fort Walton Beach Florida Activities",
    type: "checkbox",
    options: [
      "7D Movie Ride",
      "Air Force Armament Museum",
      "AMC Theatre",
      "Big Kahuna's Water Park",
      "Bike Rentals",
      "Bodywork & Massage",
      "Cattywampus Eco Adventures",
      "Crab Island Watersports",
      "Deep Sea Fishing Party Boat",
      "Destin Airboat Tours",
      "Destin Parasailing Adventure",
      "Destin Water Taxi",
      "Dolphin Watch Cruise",
      "Downtown Cinema Plus",
      "Dragonfly Yoga",
      "Emerald Coast Science Center",
      "Escape Zone 60",
      "Fat Daddy's Arcade",
      "Fishing with Kids",
      "Fort Walton Beach Parasail",
      "Golf Cart",
      "Goofy Golf",
      "Gulfarium Marine Adventure Park",
      "Heritage Park",
      "Howl at the Moon",
      "Indian Temple Mound Museum",
      "Local Fitness Center",
      "Massage Envy Spa",
      "Miracle Strip Parkway",
      "Okaloosa Island",
      "Okaloosa Island Pier",
      "Okaloosa National Mini Golf",
      "Okaloosa Island Boardwalk",
      "Pickleball",
      "Racetrack Bingo",
      "Sea Lion Show",
      "The Block 3 Clubs in 1",
      "The Emerald Cork",
      "The Swamp Club",
      "Waverunner Rental / Wet N' Wild",
      "Wild Willy's Adventure Zone"
    ],
  },
   {
    title: "Fort Walton Beach Florida Restaurants",
    type: "checkbox",
    options: [
      "Ali Baba Grill Cafe",
      "Ali's Bistro",
      "Angler's Beachside Grill",
      "Asiago's Skillet",
      "Bay Cafe",
      "Blue Collar Cafe",
      "Buffalo's Reef",
      "Burrito Del Sol",
      "Caffe Italia",
      "Clemenza's at Uptown",
      "Corner Cafe",
      "Dosirak House Inc",
      "Floyd's Shrimp House",
      "Fokker's Pub",
      "Fudpucker's Bar & Grill",
      "Fusion Bistro",
      "Helen Back Cafe",
      "Hickory River Smokehouse",
      "High Tide Restaurant/Oyster Bar",
      "IHOP",
      "Jin Jin Chinese",
      "Juno's Sushi-Steak & Seafood",
      "K.C.’s Sandbar & Grill",
      "Kim's Restaurant",
      "Kinfolks BBQ",
      "Lanie's Kitchen II",
      "LongHorn Steakhouse",
      "Los Rancheros",
      "Luxe Sports Grill",
      "Ma Ma Nu's Kitchen",
      "Magnolia Grill",
      "Mary's Kitchen",
      "Momma Goldberg’s Deli",
      "Mother Earth's Cafe",
      "Neighborhood Cafe",
      "Okinawa Japanese Restaurant",
      "Old Bay Steamer",
      "Olive Garden",
      "Original Water Front Crab Shack",
      "Pandora's Steak House",
      "Props Brewery & Grill",
      "Props Craft Brewery & Grill",
      "Rick's Crab Trap",
      "Rockin Tacos Grill & Tequila Bar",
      "Sabor A Mexico",
      "Salty Duck",
      "Shrimp Basket",
      "Siam Garden Cafe",
      "Sonny's BBQ",
      "Sotol Tequila & Mezcal",
      "Stewby's Seafood Shanty",
      "Thai House",
      "Thai Kitchen",
      "The Bangkok House Thai",
      "The Black Pearl",
      "The Boardroom Pub & Grub",
      "The Crab Trap",
      "Tijuana Flats",
      "Tops Choice Hamburgers"
    ],
  },
   {
    title: "Freeport Florida Activities",
    type: "checkbox",
    options: [
      "Eden Gardens State Park",
      "Florida Boy Adventures",
      "Freeport Plaza",
      "Outpost for Bikers",
      "Sail Destin",
      "The Rental Shop",
      "Valentine Scuba Divers",
      "Windswept Dunes Golf Course"
    ],
  },
   {
    title: "Freeport Florida Restaurants",
    type: "checkbox",
    options: [
      "3 Son's BBQ",
      "Black Creek Cafe",
      "Cafe 20",
      "Freeport Cafe",
      "Hardee's",
      "Hungry Howie's Pizza",
      "JB's Chinese Buffet",
      "L.C.'s Pizza & Subs",
      "Lucky Star",
      "Nick's Seafood",
      "Sweet Southern Comfort",
      "The Outpost"
    ],
  },
   {
    title: "Gulf Breeze Florida Activities",
    type: "checkbox",
    options: [
      "Bay Breeze Dive Center",
      "Bite Back Charters",
      "Breeze Cinema 8",
      "Bridge Bar",
      "Coastal Paddle",
      "Fish Happens Charters",
      "Fish Time Charters",
      "Fishin' Chix",
      "Gulf Breeze Flea Market",
      "Gulf Breeze Zoo",
      "Innerlight Surf & Skate",
      "Iron Gargoyle Antique Mall",
      "Massage Envy",
      "Pickleball",
      "Retro Rides",
      "Third Base Pub",
      "Tiger Point Golf Club",
      "Tree House Cinema"
    ],
  },
   {
    title: "Gulf Breeze Florida Restaurants",
    type: "checkbox",
    options: [
      "Aegean Breeze",
      "Alfredo's Mexican Cafe",
      "Crabs We Got Em",
      "Flounders Chowder",
      "Fuji Steak House",
      "IHOP",
      "James Kitchen",
      "La Brisa",
      "Mariachi's Mexican Grill",
      "Panera Bread",
      "Santino's Gulf Breeze",
      "Shan Kishi Hibachi",
      "Shanes Rib Shack",
      "Thai 54",
      "The Fishing Hole",
      "Waffle House"
    ],
  },
   {
    title: "Gulf Shores Alabama Activities",
    type: "checkbox",
    options: [
      "Air Tours Beach Flight Aviation",
      "Alabama Gulf Coast Zoo",
      "Alligator Alley",
      "Beach Flight Aviation",
      "Bike Rentals",
      "Blue Sky Parasail",
      "Cobb Theatres",
      "Cool Change Charters Tours",
      "Dolphin & Whale Watching",
      "Down Under Dive Shop",
      "Fat Daddy's Arcade",
      "Fish-Kabob Bow Fishing",
      "Fishing Charters & Tours",
      "Fly the Beach Aerial Tours",
      "GoGo Kayaks",
      "Golf Cart Rental",
      "Gulf Adventure Center",
      "Gulf Adventures Fishing",
      "Gulf Coast Escape Room",
      "Gulf Coast Tennis Club",
      "Gulf Shores Golf Club",
      "Gulf Shores Museum",
      "Hangout Music Festival",
      "Hummingbird Ziplines",
      "Ike's Beach Service",
      "Island Life Beach Rentals",
      "Kiva Dunes Golf Club",
      "Local Fitness Center",
      "Lost Bay Charters",
      "Miniature Golf Pirate's Island",
      "Nicole Fishing Charters",
      "Peninsula Golf Club",
      "Perdido Key Parasail",
      "Pink Pony Pub Beach Bar",
      "Pirate's Island Adventure Golf",
      "Pleasure Island Parasailing",
      "Reel Attraction Charters",
      "Sightseeing Wild Native Tours",
      "Spas - Austin Massage",
      "Tanger Outlet Center",
      "The Amphitheater",
      "The Track Family Rec Center",
      "Waterville USA",
      "Wild Native Tours",
      "Zeke’s Landing",
      "Zooland Mini Golf"
    ],
  },
   {
    title: "Gulf Shores Alabama Restaurants",
    type: "checkbox",
    options: [
      "Acme Oyster House",
      "Aji Sai Asian Cuisine",
      "Bahama Bobs Beach Side Cafe",
      "Behind the Pines",
      "Bill’s By the Beach",
      "Bubba's Seafood",
      "Cactus Flower Cafe",
      "Cafe Beignets",
      "Cobalt",
      "Cosmo's",
      "Cotton's Restaurant",
      "Crico's Pizza & Subs",
      "DeSoto's Seafood Kitchen",
      "Doc's Seafood Shack",
      "Duck's Diner",
      "Fish River Grill",
      "Flip Flop Deli Shop",
      "Franco's Italian",
      "Gulf Island Grill",
      "Gulf Shores Steamer",
      "Gulf State Park - Best Beach",
      "Happy Harbor Pizza",
      "Hazel's Family Seafood",
      "Hazel's Nook",
      "Hog Wild BBQ",
      "Island Pancake House",
      "Janino's Pizza",
      "King Neptune's Seafood",
      "Kitty's Kafe",
      "Lambert's",
      "Live Bait",
      "LuLu's",
      "Mikato Japanese",
      "Mikee's Seafood",
      "Mojo's Seafood & Chicken",
      "Mudbugs Seafood Bar & Grill",
      "Nolan's Lounge",
      "Original Oyster House",
      "Papa Rocco's",
      "Papa's Pizza",
      "Peninsula Restaurant & Grill",
      "Pink Pony Pub",
      "Rafters",
      "Ribs & Reds",
      "Sea N Suds",
      "Shrimp Basket",
      "Sunset Cork Room",
      "Tacky Jacks",
      "Tequila Mexican",
      "The Cove Bar and Grill",
      "The Diner",
      "The Flying Harpoon",
      "The Hangout",
      "The Steamer & Baked Oyster",
      "The Tin Top Oyster Bar",
      "Villaggio Grille",
      "West Beach Grille",
      "Wintzell's Oyster House"
    ],
  },
   {
    title: "Navarre Florida Activities",
    type: "checkbox",
    options: [
      "Champion Charters",
      "Cricket's Hideout",
      "Emerald Ghost Charters",
      "Flat Out Inshore Charters",
      "Fly The Boat Parasailing",
      "Full Net Fishing Charters",
      "Hidden Creek Golf Club",
      "Lucky Chuck Charters",
      "Navarre Beach",
      "Navarre Beach Fishing Pier",
      "Navarre Beach Inshore Charters",
      "Navarre Beach Kayaks",
      "Navarre Family Watersports",
      "Showintail Inshore Charters",
      "Wabi Sabi Day Spa"
    ],
  },
   {
    title: "Navarre Florida Restaurants",
    type: "checkbox",
    options: [
      "All American Hero's",
      "Alphy's Catfish House",
      "Cactus Flower Cafe",
      "Creekside Southern Grill",
      "Dirt Road Cookers",
      "East Bay Crab House",
      "East River Smokehouse",
      "Hachi Japanese Grill",
      "Helen Back Again",
      "JJ Chago's",
      "Johnny Huston's Grille",
      "New York Pizza Depot",
      "Sal's Pizzeria & Grill",
      "Scooter's Fish House",
      "Shrimp Basket",
      "Slippery Mermaid Sushi Bar",
      "TC's Front Porch",
      "Thailand's Best",
      "The Rib Shack",
      "Vinnie R's Italian"
    ],
  },
   {
    title: "Near By Activities",
    type: "checkbox",
    options: [
      "Area Golf",
      "Fishing",
      "Horseback Riding",
      "Jet Skiing",
      "Kayaking",
      "Live Entertainment",
      "Movie Theatre",
      "Outlet Stores",
      "Shopping Malls",
      "Walking Tours"
    ],
  },
   {
    title: "Near by Attractions",
    type: "checkbox",
    options: [
      "Lake View",
      "Near Golf",
      "Near Restaurants",
      "Near Shopping"
    ],
  },
  {
    title: "Orange Beach, Alabama Activities",
    type: "checkbox",
    options: [
      "ABC Parasail",
      "Adventure Island",
      "Beach Bike Rentals",
      "Blalock Seafood Market",
      "Boat Rentals",
      "Breakout Game",
      "Coast Cab",
      "Coastal Kayak Excursions",
      "Dolphin Fun Cruises",
      "Dolphin Tales",
      "Dolphin Tours",
      "Fat Daddy's Arcade",
      "Freebird Charters",
      "Getaway Charters",
      "Golf Course",
      "Happy Harbor",
      "Helicopter Tours",
      "Orange Beach Sailing Charters",
      "Paddled by You",
      "The Wharf",
      "Wahoo Watersports"
    ],
  },
  {
    title: "Orange Beach, Alabama Restaurants",
    type: "checkbox",
    options: [
      "Anchor Bar & Grill",
      "Brick & Spoon",
      "Cafe Grazie",
      "Cayman Grill",
      "Cobalt",
      "Cosmo's",
      "Cotton's",
      "Doc's Seafood Shack",
      "Fisher's",
      "Gilbey's Seafood",
      "Ginny Lane Bar & Grill",
      "Gulf Shores Steamer",
      "Hazel's Family Seafood",
      "Live Bait",
      "Shipp's Harbour",
      "Shrimp Basket",
      "The Gulf",
      "Villaggio Grille",
      "Voyagers"
    ],
  },
  {
    title: "Panama City Beach, Florida Activities",
    type: "checkbox",
    options: [
      "Aerial Adventures",
      "Aqua Park",
      "Barnacle Bay",
      "Beachfront Adventure Park",
      "Bike Rentals",
      "Bike the Beach",
      "Bubble Soccer LOCO",
      "Captain Anderson's Marina",
      "Club La Vela",
      "Cobra Adventure Park",
      "Coconut Creek Park",
      "Dave & Buster's",
      "Duck Adventure Tours",
      "Emerald Falls Family Rec Center",
      "Escape Zone 60",
      "Flippers Dolphin Tours",
      "Frank Brown Park",
      "Fun Land Arcade",
      "Golf Cart Rental",
      "Goofy Golf",
      "Gulf World Marine Park",
      "Hidden Lagoon",
      "Indy Speedway",
      "Island Air Express",
      "Island Time Boat Tours",
      "Jet Skis - Adventures at Sea",
      "Lagoon Pontoons",
      "Local Fitness Center",
      "Marcus' Gulf Pizza",
      "Mirror Maze & Laser Craze",
      "Panama City Airboat Tours",
      "Panhandle Helicopter",
      "Paradise Adventures Catamaran",
      "PCB Aquatic Center",
      "Pier Park",
      "Reel Contender Fishing Charter",
      "Sandpiper Tiki Bar",
      "Scampys Seafood",
      "Shell Island",
      "Shipwreck Island Water Park",
      "Skydive Panama City",
      "The Grand Theatre",
      "Wild Thang Airboat Tours",
      "WonderWorks",
      "ZooWorld"
    ],
  },
  {
    title: "Panama City Beach, Florida Restaurants",
    type: "checkbox",
    options: [
      "Andy's Flour Power",
      "Angelo's Steak Pit",
      "Another Broken Egg",
      "Bayou on the Beach",
      "Billy's Oyster Bar",
      "Bonefish Grill",
      "Boon Dock's Restaurant",
      "Capt. Anderson's",
      "Carrabba's",
      "Chicken Salad Chick",
      "Dat Cajun Place",
      "David's Cafe",
      "Dee's Hang Out",
      "Dick's Last Resort",
      "Dirty Dick's Crab House",
      "Dusty's Oyster Bar",
      "Edgewater Waffle Shop",
      "Finn's Island Style Grub",
      "Firefly",
      "Hammerhead Fred's",
      "Harpoon Harry's",
      "Hook'd Pier Bar and Grill",
      "J Michael's",
      "Jeannie's One Stop Diner",
      "Ketana Restaurant",
      "Liza's Kitchen",
      "Margaritaville",
      "Mike's Cafe and Oyster Bar",
      "Moe's Original BBQ",
      "Montego Bay Seafood",
      "Pineapple Willy's",
      "Pompano Joe's",
      "Pompano Key",
      "Red Rae's",
      "Runaway Island",
      "Saltwater Grill",
      "Salty Sue's",
      "Salvatore's Pizza",
      "Schooners",
      "Sharky’s Beachfront",
      "Shuckums Oyster Pub",
      "Spinnaker Beach Club",
      "The Back Porch",
      "The Boar's Head",
      "The Egg and I",
      "The Terrace Restaurant",
      "The Wharf Seafood Buffet",
      "The Wicked Wheel",
      "Thomas Donut Shop",
      "Triple J Steak & Seafood"
    ],
  },
    {
    title: "Pensacola Florida Activities",
    type: "checkbox",
    options: [
      "A Reel Eazy Charter",
      "A.C. Read Golf Course",
      "Aquatic Charters Chase-N-Fins",
      "Bike Rentals",
      "Bonelli's",
      "Bonifay Water Sports",
      "Cavu Club",
      "Chase-N-Fins",
      "Condor Sailing Adventures",
      "Cordova Mall",
      "DeLuna Lanes",
      "Dolphin Express",
      "Escape On Palafox - Escape Room",
      "Fast Eddie's Fun Center",
      "Fiesta of Five Flags",
      "Flora-Bama Lounge",
      "Go Retro",
      "Good Time Tours, Inc.",
      "Gulfarium",
      "Historic Pensacola Village",
      "Key Sailing",
      "Landshark Landing",
      "Lost Key Golf Club",
      "Marcus Pointe Golf Club",
      "Oscar's",
      "Outdoor Gulf Coast",
      "Pensacola Greyhound Track",
      "Pensacola Ice Flyers",
      "Pensacola Interstate Fairgrounds",
      "Pensacola Little Theatre",
      "Pensacola Opera",
      "Pensacola Paddlesport Rentals",
      "Premier Dolphin Cruises",
      "Quayside Art Gallery",
      "Sam's Fun City & Surf City",
      "Seville Quarter",
      "Vinyl Music Hall"
    ],
  },
    {
    title: "Pensacola Florida Restaurants",
    type: "checkbox",
    options: [
      "Adventures Unlimited",
      "Another Broken Egg",
      "Atlas Oyster House",
      "Blue Dot Barbecue",
      "Bonefish Grill",
      "Captain Joey Patti's Seafood",
      "Carmen's Lunch Bar",
      "Carrabba's",
      "CJ'S Kitchen & Grille",
      "Coffee Cup Restaurant",
      "Dharma Blue",
      "Five Sisters Blues Cafe",
      "Franco's Italian",
      "Fuji Sushi Bar & Grill",
      "Hot Spot Barbecue",
      "Hummus",
      "Ichiban",
      "IRON",
      "Jackson's Steakhouse",
      "Jaco's Bayfront Bar & Grille",
      "Jerry's Drive In",
      "Just Fish & Grits",
      "Kappa Japanese",
      "Khon's on Palafox",
      "Marina Oyster Barn",
      "McGuire's Irish Pub",
      "New Yorker Deli",
      "Nick's Boathouse",
      "O'Briens Bistro",
      "Pensacola Cooks Kitchen",
      "Polonza Bistro",
      "Rodizio Grill",
      "Romano's Macaroni Grill",
      "Shark Fin",
      "Shux Oyster Bar",
      "Sumo Sushi",
      "Taco Rock",
      "The Fish House",
      "The Fishing Hole Resturant",
      "The Global Grill",
      "The Magnolia",
      "The Oar House",
      "Tu-Do Vietnamese",
      "Tuscan Oven",
      "Xiscali Mexican"
    ],
  },
   {
    title: "Perdido Key Florida Activities",
    type: "checkbox",
    options: [
      "All Jack'd Up Charters",
      "Big Lagoon State Park",
      "Cordova Mall",
      "Emerald Oasis Day Spa",
      "Little Heads Kayaks",
      "Lost Key Golf Club",
      "Megabite Inshore Charters",
      "Outcast Charter Docks",
      "Perdido Bay Golf Club",
      "Perdido Massage",
      "Powers Fishing",
      "Tanger Outlet",
      "The Market",
      "The Wharf"
    ],
  },
  {
    title: "Perdido Key Florida Restaurants",
    type: "checkbox",
    options: [
      "Bella Luna Pizza",
      "Cobalt",
      "Cosmo's",
      "Fisherman's Corner",
      "Hub Stacy's",
      "Lillian's Pizza",
      "Original Pointe",
      "Rib Shack",
      "Sunset Grille",
      "The Crab Trap",
      "The Oyster Bar",
      "The Sports Bar",
      "Triggers Seafood"
    ],
  },
   {
    title: "Recommended For",
    type: "checkbox",
    options: [
      "Adventure Trip",
      "Beach Rentals",
      "Children Retreat",
      "Golf",
      "Lake",
      "Long Term Rentals",
      "Romantic"
    ],
  },
];