export const amenitiesData = [
  {
    title: "Barbecue - Grills",
    type: "checkbox",
    options: [
      "Community Charcoal Grill",
      "Community Gas Grill",
      "Private BBQ",
      "Private Charcoal Grill",
      "Private Gas Grill",
      "Charcoal Grill",
      "Gas Grill",
      "Electric Grill",
    ],
  },
  {
    title: "Bathroom",
    type: "checkbox",
    options: [
      "Bathtub",
      "Linens & Towels",
      "Private Bathroom",
      "Grab Bars",
      "Shower/Tub Combo",
      "Walk in Shower",
      "Freestanding Bathtub",
      "Whirlpool/Jacuzzi Bathtub",
      "Hairdryer",
    ],
  },
  {
    title: "Bedroom Setup",
    type: "checkbox",
    name: "bedroom_setup",
    options: [
      "1 Bunk Bed",
      "1 Double Bed",
      "1 Futon",
      "7 King Beds",
      "1 Queen Bed",
      "3 Sofa Beds",
      "3 Twin Beds",
      "1 King Bed",
      "2 King Beds",
      "3 King Beds",
      "4 King Beds",
      "5 King Beds",
      "6 King Beds",
      "2 Queen Beds",
      "3 Queen Beds",
      "4 Queen Beds",
      "5 Queen Beds",
      "Queen Bed",
      "2 Full Beds",
      "3 Full Beds",
      "4 Full Beds",
      "5 Full Beds",
      "2 Futons",
      "3 Futons",
      "4 Futons",
      "5 Futons",
      "1 Twin Bed",
      "2 Twin Beds",
      "2 Bunk Beds",
      "3 Bunk Beds",
      "4 Bunk Beds",
      "1 Full Bed",
      "Trundle Bed",
      "1 Sofa Bed",
      "2 Sofa Beds",
      "Roll Away Bed",
      "2 Double Beds",
      "4 Twin Beds",
      "4 Sofa beds",
      "6 Bunk Beds",
      "9 Twin Beds",
      "8 Full Beds",
      "6 Twin Beds",
      "8 King Beds",
      "14 Twin Beds",
      "Bunk Room",
      "8 Queen Beds",
      "3 Trundle Beds",
      "8 Twin Beds",
      "9 King Beds",
      "10 Roll Away Beds",
      "10 Trundle Beds",
      "6 Roll Away Beds",
      "5 Twin Beds",
      "10 Queen Beds",
      "8 Futons",
      "10 Bunk Rooms",
      "8 Trundle Beds",
      "9 Roll Away Beds",
      "10 Bunk Beds",
      "6 Double Beds",
      "2 Trundle Beds",
      "4 Double Beds",
      "10 Double Beds",
      "10 Sofa Beds",
      "5 Sofa Beds",
      "8 Double Beds",
      "4 Roll Away Beds",
      "6 Futons",
      "4 Bunk Rooms",
      "5 Roll Away Beds",
      "3 Bunk Rooms",
      "9 Bunk Rooms",
      "10 Futons",
      "7 Roll Away Beds",
      "5 Trundle Beds",
      "10 Twin Beds",
      "7 Queen Beds",
      "10 Full Beds",
      "9 Futons",
      "5 Bunk Rooms",
      "7 Bunk Rooms",
      "10 King Beds",
      "5 Double Beds",
      "8 Roll Away Beds",
      "9 Sofa Beds",
      "6 Bunk Rooms",
      "6 Trundle Beds",
      "7 Futons",
      "2 Roll Away Beds",
      "3 Double Beds",
      "9 Full Beds",
      "8 Bunk Rooms",
      "9 Bunk Beds",
      "3 Roll Away Beds",
      "8 Sofa Beds",
      "9 Queen Beds",
      "7 Double Beds",
      "9 Double Beds",
      "6 Full Beds",
      "2 Bunk Rooms",
      "7 Bunk Beds",
      "9 Trundle Beds",
      "7 Full Beds",
      "4 Trundle Beds",
      "6 Sofa Beds",
      "7 Sofa Beds",
      "7 Twin Beds",
      "6 Queen Beds",
      "7 Trundle Beds",
      "8 Bunk Beds",
    ],
  },
  {
    title: "Bedroom Extras",
    type: "checkbox",
    options: [
      "Private Bathroom",
      "Walk-in Closet",
      "Alarm Clock",
      "Balcony/Patio off Master",
      "Fireplace",
      "Skylight",
      "Crib",
      
    ],
  },
   {
    title: "Boating",
    type: "checkbox",
    options: [
      "Boat Included",
      "Boat Rental Available",
      "Marina",
      "Pier",
      "Boat Parking Nearby",
      "Trailer Parking Nearby",
      "Boat Slip Included",
      
    ],
  },
   {
    title: "Cooling Comfort",
    type: "checkbox",
    options: [
      "Ceiling Fans",
      "Central Air Conditioning",
      "Window A/C Units",
      
    ],
  },
   {
    title: "Dining Room",
    type: "checkbox",
    options: [
      "Dining Table",
      "Eat in Counter",
      "Eat in Kitchen",
      "Formal Dining Room",
      
      
    ],
  },
   {
  title: "Disability Access Features",
  type: "checkbox",
  options: [
    "Grab Bars in Bathroom",
    "Ground Floor Unit",
    "Safety Bars in Shower",
    "Single Level - No Stairs",
    "Television Amplifier",
    "Walk-in Shower",
    "Handicap Accessible",
  ],
}
,
   {
    title: "Entertainment",
    type: "checkbox",
    options: [
      "Big Screen TV",
      "Boating",
      "Cable TV",
      "CD Stereo",
      "DVD Library",
      "DVD Player",
      "Fishing",
      "Golf",
      "Gaming Consoles",
      "Jet Ski",
      "Kayaking",
      "Minature Golf",
      "CD Player",
      "Scuba",
      "Snorkling",
      "Stereo",
      "Swimming",
      "Television",
      "TV/DVD",
      "TV/VCR",
      "VCR",
      "Video Library",
      "DVD/VCR",
      "Smart T.V.",
      "Ox Cord",
      "Bluetooth Speaker",
      "Netflix",
      "Bikes Included",
      "Wedding Friendly",
      
    ],
  },
   {
     title: "Games",
    type: "checkbox",
    options: [
      "Board Games",
      "Reading Library",
      "Foosball",
      "Ping Pong Table",
      
    ],
  },
   {
    title: "General",
    type: "checkbox",
    options: [
      "Linens Included",
      "No Pets",
      "No Smoking",
      "Pets On Request",
      "Pet Friendly",
      "Smoking outside only",
      "Telephone",
      "Voicemail",
      "Cell Phone",
      "Vacuum",
      "Fitness Center",
      "Smoking Permitted",
      "Condo",
      "Home",
      "Townhouse",
      "Pack and Play",
      "High Chairs",
      "Elevator/Lift",
      "Online Booking",
      "Extra Housekeeping",
      "Managed By Owner",
      "Managed by Property Manager",
      
    ],
  },
   {
    title: "Kitchen",
    type: "checkbox",
    options: [
      "Washer/Dryer",
      "Blender",
      "Breakfast Bar",
      "Can Opener",
      "Coffee Maker",
      "Dishes",
      "Dishwasher",
      "Disposal",
      "Fully Equipped Kitchen",
      "Garbage Compactor",
      "Gourmet Kitchen",
      "Ice Maker",
      "Ironing Board",
      "Kitchenette",
      "Microwave",
      "Mixer",
      "Oven",
      "Pots and Pans",
      "Refrigerator",
      "Stove",
      "Toaster",
      "Utensils",
      "Water Filter",
      "Crock Pot",
      "Keurig",
      "Wet Bar",

      
    ],
  },
   {
    title: "Outside Living",
  type: "checkbox",
  options: [
    "BBQ Grill",
    "Community Pool",
    "Deck",
    "Outside Shower",
    "Patio",
    "Porch",
    "Porch Furniture",
    "Private Parking",
    "Private Pool",
    "Restaurants",
    "Water Park & Wildlife Viewing",
    "Indoor pool",
    "Golf Cart Included",
    "Gulf/Ocean View",
    "Gulf/Ocean Front",
    "Balcony",
    "Beach Chairs Provided",
    "Beach Service Provided",
    "View (Water)",
    "View (Lake)",
    "Waterfront",
    "Beachfront",
    "Hot Tub/Heated Spa",
    "Boat Dock",
    "Fenced yard",
    "LSV (Low Speed Vehicle)",
      
    ],
  },
   {
 title: "Parking",
  type: "checkbox",
  options: [
    "Covered",
    "Driveway",
    "On Street",
    "Parking Available",
    "Parking for 1 car",
    "Parking for 2 cars",
    "Parking for 3 cars",
    "Parking for 4 cars",
    "Parking for 5 cars",
    "Parking for 6 cars",
    "Garage Included",
    "Parking for 7 cars",
    "Parking for 8 cars",
    "Parking for 9 cars",
    "Parking for 10 + cars",
    "RV Parking Nearby",
      
    ],
  },
   {
    title: "Home Office",
    type: "checkbox",
    options: [
      "High Speed Internet Access",
      "Meeting Room",
      "Wireless Internet Access",
     
      
    ],
  },
//    {
//     title: "Bedroom Extras",
//     type: "checkbox",
//     options: [
//       "Private Bathroom",
//       "Walk-in Closet",
//       "Alarm Clock",
//       "Balcony/Patio off Master",
//       "Fireplace",
//       "Skylight",
//       "Crib",
      
//     ],
//   },
];
